apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: jufuku-secret-provider
spec:
  provider: azure
  secretObjects: # secretObjects defines the desired state of synced K8s secret objects
  - secretName: jufuku-secret
    type: kubernetes.io/tls
    data:
    - objectName: admincert
      key: tls.key
    - objectName: admincert
      key: tls.crt
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: ac70caf1-bdec-4b89-8f55-8d2fefd2519d
    keyvaultName: jufukukv01 # the name of the AKV instance
    objects: |
      array:
        - |
          objectName: admincert
          objectType: secret
    tenantId: 72f988bf-86f1-41af-91ab-2d7cd011db47 # the tenant ID of the AKV instance
