
apiVersion: storage.k8s.io/v1
kind: StorageClass 
metadata:   
  name: {{ .Values.projectRoot.kind.storageClass.managedcsi.metadata.name}} 
provisioner: {{ .Values.projectRoot.kind.storageClass.managedcsi.metadata.provisioner}}


---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.projectRoot.kind.statefulset.metadata.name}}
  labels: {{- toYaml .Values.projectRoot.kind.statefulset.metadata.labels | nindent 4}}
spec:
  replicas: {{ .Values.projectRoot.kind.statefulset.spec.replicas}}
  serviceName: {{ .Values.projectRoot.kind.statefulset.spec.serviceName}}
  selector:
    matchLabels: {{- toYaml .Values.projectRoot.kind.statefulset.spec.selector.matchLabels | nindent 6}}
  template:
    metadata:
      labels: {{- toYaml .Values.projectRoot.kind.statefulset.spec.template.metadata.labels | nindent 8}}
    spec:
      serviceAccountName: {{ include "jufukuproject.serviceAccountName" . }}
      securityContext:
      containers:
      - name: {{ .Values.projectRoot.kind.statefulset.spec.template.spec.containers.name}}
        image: {{ .Values.projectRoot.kind.statefulset.spec.template.spec.containers.image}}
        env: {{- toYaml .Values.projectRoot.kind.statefulset.spec.template.spec.containers.env | nindent 10}}
        resources: {{- toYaml .Values.projectRoot.kind.statefulset.spec.template.spec.containers.resources | nindent 10}}
        ports: {{- toYaml .Values.projectRoot.kind.statefulset.spec.template.spec.containers.ports | nindent 10}}
        volumeMounts: {{- toYaml .Values.projectRoot.kind.statefulset.spec.template.spec.containers.volumeMounts | nindent 10}}
  volumeClaimTemplates:
  - metadata:
      name: {{ .Values.projectRoot.kind.statefulset.spec.volumeClaimTemplates.metadata.name}}
    spec: {{- toYaml .Values.projectRoot.kind.statefulset.spec.volumeClaimTemplates.spec | nindent 6}}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.projectRoot.kind.service.db.metadata.name}}
  labels: {{- toYaml .Values.projectRoot.kind.service.db.metadata.labels | nindent 4}}
spec:
  type: {{ .Values.projectRoot.kind.service.db.spec.type}}
  selector: {{- toYaml .Values.projectRoot.kind.service.db.spec.selector | nindent 4}}
  ports: {{- toYaml .Values.projectRoot.kind.service.db.spec.ports | nindent 4}}

