version: '3'
services:
  db: 
    build: ./db
    image: jufukuacr01.azurecr.io/db:v1.0.0
    env_file:
      - ./db/values.env
    expose:
      - "5432"

  application:
    build: ./application
    image: jufukuacr01.azurecr.io/application:v1.4.0
    env_file:
      - ./application/values.env
    expose:
      - "8000"
    command: /bin/sh -c "sleep 30 && python manage.py collectstatic --no-input && python manage.py migrate && gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    depends_on:
      - db
  
  web:
      build: ./web
      image: jufukuacr01.azurecr.io/web:v1.1.0
      ports:
        - '8090:80'
      env_file:
        - ./web/values.env
      command: /bin/sh -c "envsubst '$$APP_SERVICE_NAME $$APP_HOST_NAME' < /etc/nginx/conf.d/appservers.conf.template > /etc/nginx/conf.d/appservers.conf && nginx -g 'daemon off;'"
      depends_on:
        - application
