apiVersion: v1
entries:
  jufukuproject:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-05-01T22:22:11.1974382+09:00"
    description: A Helm chart for Kubernetes
    digest: 444d0ba2cf64fbabe3ec33485be86e96e16d51ae14c58cdb0b0095aaed51c4f1
    name: jufukuproject
    type: application
    urls:
    - jufukuproject-1.0.0.tgz
    version: 1.0.0
generated: "2023-05-01T22:22:11.1944405+09:00"
